--- 
- include_tasks: "{{start_mail}}"
- block:

    - name: Disabling UAC in Windows VM
      win_regedit:
       path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
       name: EnableLUA
       data: 0
       type: dword
      register: result

    - name: Sending the success mail
      include_tasks: "{{success_mail}}"
      when: result is changed


  rescue:
   - debug: 
       msg: "The failed task was :  {{ ansible_failed_task.name }} for the role called   {{ role_name }}  of hostname  {{ hostvars[inventory_hostname]['inventory_hostname'] }}"
     register: output

   - name: setting the facts
     set_fact:
        failmsg: "{{ output }}"

   - name: Task failed
     include_tasks: "{{failure_mail}}"
