---
- include_tasks: "{{start_mail}}"
- block:

  - name: Collect the facts of the windows systems
    setup:
    register: winfacts

  - name: Configure domain name for the network in Windows
    win_shell: Get-NetAdapter -Name "{{adapter_name}}" | Set-DnsClient -ConnectionSpecificSuffix "{{dns_suffix_name}}"
    register: dns_suffix
    when:  winfacts.ansible_facts.ansible_interfaces[item|int].connection_name is defined and  adapter_name ==  winfacts.ansible_facts.ansible_interfaces[item|int].connection_name
    with_sequence: start=0 end="{{ winfacts.ansible_facts.ansible_interfaces | length |int -1}}" stride=1
 
  - name: Sending the success mail
    include_tasks: "{{success_mail}}"
    when: dns_suffix is success

  rescue:
   - debug: 
       msg: "The failed task was :  {{ ansible_failed_task.name }} for the role called   {{ role_name }}  of hostname  {{ hostvars[inventory_hostname]['inventory_hostname'] }}"
     register: output

   - name: setting the facts
     set_fact:
        failmsg: "{{ output }}"

   - name: Task failed
     include_tasks: "{{failure_mail}}"