---
- include_tasks: "{{start_mail}}"
- block:
   
    - name: Fetching Pagefile Size Information
      win_pagefile:
          state: query
      register: pagefile
    - debug: msg="{{pagefile}}"

   
    - name: Fix PageFile Size For  C Drive
      win_pagefile:
          drive: C
          initial_size: "{{pagefile_initial_size}}"
          maximum_size: "{{pagefile_maximum_size}}"
          state: present
      register: result

    - name: Sending the success mail
      include_tasks: "{{success_mail}}"
      when: result is success
 

  rescue:
   - debug: 
       msg: "The failed task was :  {{ ansible_failed_task.name }} for the role called   {{ role_name }}  of hostname  {{ hostvars[inventory_hostname]['inventory_hostname'] }}"
     register: output

   - name: setting the facts
     set_fact:
        failmsg: "{{ output }}"

   - name: Task failed
     include_tasks: "{{failure_mail}}"
